services:
  - type: web
    name: snout-form
    runtime: node
    plan: starter
    buildCommand: npm install && npx prisma generate --schema=prisma/schema.prisma && npx prisma migrate deploy --schema=prisma/schema.prisma && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20.x
      - key: NODE_ENV
        value: production
      - key: NEXT_PUBLIC_APP_URL
        value: https://snout-form.onrender.com
    healthCheckPath: /api/health

